version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/diary-server
    file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/stop.sh
  ApplicationStart:
    - location: scripts/start.sh