# JPA sql 로그에 바인딩 된 파라미터 출력
logging.level.org.hibernate:
  SQL: debug
#  type:
#    descriptor:
#      sql: trace

spring:
  config:
    import: application-secret.yml

  jpa:
    properties:
      hibernate:
        # DB 방언 설정
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        default_batch_fetch_size: 500
        # JPA sql 쿼리 로그 출력
        highlight_sql: true
        format_sql: true

    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true

  datasource:
    hikari:
      idle-timeout: 300
      max-lifetime: 300

  servlet:
    multipart:
      # 한 파일의 최대 크기
      max-file-size: 20MB
      # 한 요청의 최대 크기
      max-request-size: 100MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jackson:
    serialization:
      fail-on-empty-beans: false

  data:
    web:
      pageable:
        one-indexed-parameters: true

  output.ansi.enabled: always

server:
  port: 8080
  error:
    include-stacktrace: on_param
    include-exception: true
#  servlet:
#    session:
#      timeout: 30
#      tracking-modes: cookie
