spring:
  config:
    import: application-secret.yml
  jpa:
    # JPA sql 쿼리 로그 출력
    show-sql: true
    properties.hibernate.format_sql: true

    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  servlet:
    multipart:
      # 한 파일의 최대 크기
      max-file-size: 20MB
      # 한 요청의 최대 크기
      max-request-size: 100MB

#  profiles:
#    active: secret

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jackson:
    serialization:
      fail-on-empty-beans: false

  data:
    web:
      pageable:
        one-indexed-parameters: true

  output:
    ansi:
      enabled: always
#
server:
  error:
    include-stacktrace: on_param
    include-exception: true
  servlet:
    session:
      tracking-modes: cookie

# JPA sql 로그에 바인딩 된 파라미터 출력
logging.level.org.hibernate:
  SQL: debug
  type:
    descriptor:
      sql: trace